name: ECR Push

on: [workflow_dispatch]

permissions:
  contents: read
  id-token: write

env:
  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} 
  IMAGE_TAG: ${{ github.sha }}
  ECR_URI: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OIDC Login to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.role-to-assume }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate AWS connection
        run: aws sts get-caller-identity
      
      - name: Create ECR repository and check existence
        run: |
          if ! aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }}; then
            aws ecr create-repository --repository-name ${{ env.ECR_REPOSITORY }};
          else
            echo "ECR repository ${{ env.ECR_REPOSITORY }} already exists.";
          fi
    
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }} -f app/dockerfile ./app
          docker push ${{ env.ECR_URI }}:${{ env.IMAGE_TAG }}

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'alpine:latest'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'    

      - name: Log image details
        run: |
          echo "Image pushed to ECR:"
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.IMAGE_TAG }}"

      - name: CodeQL Scan
        uses: github/codeql-action/init@v2
        with:
         languages: javascript    